version: 0.0.{build}
configuration: Release
assembly_info:
  patch: true
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
- cmd: .\merge.cmd
- ps: >-
    $version = `
      IF ($env:APPVEYOR_REPO_BRANCH -eq "master") {"$env:APPVEYOR_BUILD_VERSION-beta"} `
      ELSE { IF ($env:APPVEYOR_REPO_BRANCH -eq "test") {"$env:APPVEYOR_BUILD_VERSION-rc"} `
      ELSE {"$env:APPVEYOR_BUILD_VERSION-alpha"} }

    (Get-Content "$env:APPVEYOR_BUILD_FOLDER\Lazuli.nuspec") `
        -replace '<version>[^<]*?</version>', ('<version>{0}</version>' -f $version) |
      Out-File "$env:APPVEYOR_BUILD_FOLDER\Lazuli.nuspec"
- cmd: nuget pack
